### ISSUE TITLE
Missing LICENSE file in repository

### ISSUE THREAD

**Issue by alexanderjeurissen** [artsy/lint-changed#24]
I've noticed https://www.npmjs.com/package/@artsy/lint-changed mentions a MIT license.

A `LICENSE` file detailing this license is missing in this repository however. You can use the GitHub LICENSE templates for this: https://github.com/licenses/license-templates

**Comment by zephraph** [comment]
Thanks for the tip! That was an oversight, I'll add it.

**Comment by artsyit** [comment]
:rocket: Issue was released in [`v3.2.0`](https://github.com/artsy/lint-changed/releases/tag/v3.2.0) :rocket:
