### ISSUE TITLE
Missing install and usage sections in readme

### ISSUE THREAD

**Issue by xanderfehsenfelddelhivery** [artsy/lint-changed#60]
Do you mind adding sections to the readme about how to install and run this package?

**Comment by damassi** [comment]
Will do later today! (Surprised it's not already there)

**Comment by damassi** [comment]
See https://github.com/artsy/lint-changed/pull/61. Let me know if you think any more should be added!

**Comment by damassi** [comment]
Ah and also https://github.com/artsy/lint-changed/pull/62; i've added a full example to the repo
