### ISSUE TITLE
Warnings in eslint output treated as error

### ISSUE THREAD

**Issue by RecuencoJones** [artsy/lint-changed#66]
Some days ago while running some of our pipelines we started noticing our linter stage would fail running `lint-changed`.

Apparently, when running eslint under the hood, it would warn about browserslist:

```
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
``` 

That statement seems to be logged via [console.warn](https://github.com/browserslist/browserslist/blob/main/node.js#L395), which goes through stderr buffer and therefore makes `lint-changed` to fail with an empty red line.

<img width="122" alt="image" src="https://user-images.githubusercontent.com/7302877/200323529-14c51700-a5d8-409a-9e76-780cb4dffb15.png">

This empty line is probably due to [throwing a string](https://github.com/artsy/lint-changed/blob/main/src/lint-changed.ts#L46) and then [destructuring in catch](https://github.com/artsy/lint-changed/blob/main/src/lint-changed.ts#L49).

I'd assume only errors caught from [`await run()`](https://github.com/artsy/lint-changed/blob/main/src/lint-changed.ts#L44) should actually make `lint-staged` fail.

**Comment by damassi** [comment]
Merged!

**Comment by RecuencoJones** [comment]
Thanks!
